config/routes.rb
Rails.application.routes.draw do
  get 'blog/index'

  resources :orders
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :line_items
  resources :carts
  get 'store/index'
  get '/users' => redirect('/users/sign_up')
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
  resources :products do
    get :who_bought, on: :member
  end
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart_id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

  def line_item_params
    params.require(:line_item).permit(:product_id)
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_url, notice: "Invalid cart"
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  def goods_quantity
    current_cart.line_items.count
  end

  def cart_empty?
    goods_quantity == 0
  end
end

app/views/carts/_cart.html.erb
<h2>Your Cart</h2>
<table>
  <tbody>
    <%= render(cart.line_items) %>
    <tr class="total_line">
      <td>
        <div>
          <span>Total</span>
          <span class="total_cell"><%= number_to_currency(cart.total_price) %></span>
        </div>
      </td>
    </tr>
  </tbody>
</table>

<%= button_to "Checkout", new_order_path, class: 'btn btn-success', method: :get %>
<%= button_to '', @cart, class: 'secrete empty_cart', form_class: 'button_to new-item', method: :delete %>
<span class="btn btn-danger">Empty cart</span>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h4>
      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h2>Your cart</h2>
  <div class="carts">
    <% @cart.line_items.each do |item| %>
      <div>
        <%= item.quantity %>&nbsp;&times;&nbsp;
        <%= item.product.title %>&nbsp;&nbsp;&nbsp;
        <span class="priceLine">
          <%= number_to_currency(item.total_price) %>
        </span>&nbsp;&nbsp;&nbsp;
        <span>
          <%= link_to '', item, class: 'glyphicon glyphicon-trash', form_class: 'button_to new-item', method: :delete %>
        </span>
      </div>
    <% end %>
    <br/>
    <div class="total_line">
      <span>Total&nbsp;&nbsp;&nbsp;</span>
      <span><%= number_to_currency(@cart.total_price) %></span>
    </div>
    <%= button_to '', @cart, class: 'secrete empty_cart', form_class: 'button_to new-item', method: :delete %>
    <div class="btn btn-danger">Empty cart</div>
    <%= button_to "Checkout", new_order_path, class: 'btn btn-success', method: :get %>

  </div>