config/routes.rb
Rails.application.routes.draw do
  get 'blog/index'

  resources :orders
  devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :line_items
  resources :carts
  get 'store/index'
  get '/users' => redirect('/users/sign_up')
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
  resources :products do
    get :who_bought, on: :member
  end
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books online store</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content=""/>
  <meta name="keywords" content=""/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag :application %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
</head>
<!--https://launchschool.com/blog/how-to-use-devise-in-rails-for-authentication-->
<body>
<header class="navbar-fixed-top">
  <div class="header">
    <nav class="navbar navbar-default color1">
      <div class="container">
        <div class="row">
          <ul class="nav navbar-nav second-nav">
            <li><a href="/">
              <h1 class="logo">SOKALSHOP</h1>
              <p class="p-logo">Internet-Store</p></a>
            </li>
            <li style="float: right; padding-right: 10%">
              <%= link_to cart_path(current_cart), class: 'link-on-basket' do %>
                  <% if cart_empty? %>
                      <div class="basket"></div>
                  <% else %>
                      <div class="basket1"></div>
                  <% end %>
              <% end %>
            </li>
            <!--can add some filtering in the future-->
            <!--<li>-->
              <!--<form class="form-container">-->
                <!--<div class="form-group">-->
                  <!--<input type="text" class="form-control" id="poshuk" placeholder="Find by name">-->
                <!--</div>-->
              <!--</form>-->
            <!--</li>-->
            <!--<li>-->
              <!--<div class="dropdown">-->
                <!--<div class="dropdown-toggle" data-toggle="dropdown">Filter by-->
                  <!--<span class="glyphicon glyphicon-chevron-down"></span>-->
                <!--</div>-->
                <!--<ul class="dropdown-menu">-->
                  <!--<li><a href="#">By name</a></li>-->
                  <!--<li><a href="#">By price</a></li>-->
                <!--</ul>-->
              <!--</div>-->
            <!--</li>-->
            <li style="float: right; padding-right: 10%">
              <span class="glyphicon glyphicon-earphone"></span>
              <span class="bold">(044) 000-00-00</span>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="header">
    <nav class="navbar navbar-default navbar-inverse ">
      <div class="container">
        <div class="row">
          <ul class="nav navbar-nav first-nav">
            <% if user_signed_in? %>
              <% if current_user.email === ENV['ADMIN_EMAIL'] ||
                  current_user.email === 'roger@rubyriders.com' ||
                  current_user.email === 'sokalmet@ukr.net' %>
                <li><%= link_to 'Products', products_path %></li>
              <% end %>
            <% end %>
            <li><%= link_to 'Store', store_path %></li>
            <li><%= link_to 'Blog', blog_index_path %></li>
            <% if user_signed_in? %>
              <% if current_user.email === ENV['ADMIN_EMAIL'] ||
                  current_user.email === 'roger@rubyriders.com' ||
                  current_user.email === 'sokalmet@ukr.net' %>
                <li><%= link_to 'Orders', orders_path %></li>
              <% end %>
            <% end %>
          </ul>
          <div class="cabinet">
            <% if user_signed_in? %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-user" aria-hidden="true"></i> Logout | <%= current_user.email %>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-user" aria-hidden="true"></i> Sign in
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

<div class="wrapper clearfix">
  <div id="main">
    <% flash.each do |name, msg| %>
      <div class="alert_wrapper">
        <div class="alert alert-dismissible" role="alert">
          <%= image_tag ('messagebox_info30.png') %>
          <%= content_tag :span, msg, class: 'notice' %>
          <button type="button" class="close" data-dismiss="alert" aria-label="close">&times;</button>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="block-f">
          <h3>FOR Chill Out</h3>
          <ul>
            <li><a href="https://www.youtube.com/watch?v=hUjRuVhJ_4o">Beautiful Jazz</a></li>
            <li><a href="https://www.youtube.com/watch?v=RMiAZ1gh4R8">Benzopilin video</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <div class="block-f">
          <h3>COMPANY</h3>
          <ul>
            <li><%= link_to 'Blog', blog_index_path %></li>
            <li><a href="#">About us</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-md-offset-2">
        <div class="block-f">
          <h3>OUR PARTHNERS</h3>
          <p class="m-bottom">Some information</p>
          <div class="contacts">
            <div class="green">24/7</div>
            <div class="phone1">0 800 000 000</div>
            <div class="phone2">(044) 000 00 00</div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>

  <p class="copyright">
    Copyright &#169; 2018 https://sokalshop.herokuapp.com
  </p>

</footer>
</body>
</html>